urls.py
#
#   This file is part of cctorrent
#   Copyright (C) 2014-2015 Moritz Strohm <ncc1988@posteo.de>
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU Affero General Public License as
#   published by the Free Software Foundation, either version 3 of the
#   License, or (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU Affero General Public License for more details.
#
#   You should have received a copy of the GNU Affero General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.
#


from django.conf.urls import patterns, include, url


cctorrent_urls = patterns('',
    # Examples:
    # url(r'^$', 'cctorrent.views.home', name='home'),
    # url(r'^cctorrent/', include('cctorrent.foo.urls')),
    
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    
    # Uncomment the next line to enable the admin:
    
    url(r'^$', 'cctorrent.views.index', name='index'),
    url(r'^api', 'cctorrent.views.api', name='api'),
    url(r'^js/settings.js', 'cctorrent.views.settingsJS', name='settingsJS'),
    
    url(r'^help/TorrentClients', 'cctorrent.views.torrentClients', name='TorrentClients'),
    
    #url(r'^login', 'cctorrent.views.loginView', name='login'),
    url(r'^login', 'django.contrib.auth.views.login', {'template_name': 'cctorrent/login.html'}, name='login'),
    url(r'^logout', 'django.contrib.auth.views.logout', {'template_name': 'cctorrent/logout.html'}, name='logout'),
    
    url(r'^artist/(\d+)/$', 'cctorrent.views.artist', name='artist'),
    url(r'^artist/(\d+)/newalbum', 'cctorrent.views.newalbum', name='newalbum'),
    
    url(r'^album/(\d+)/$', 'cctorrent.views.album', name='album'),
    url(r'^album/(\d+)/finish', 'cctorrent.views.finishAlbum', name='finishAlbum'),
    
    url(r'^album/(\d+)/newtrack', 'cctorrent.views.newtrack', name='newtrack'),
    
    url(r'^tag/([a-z0-9]+)/$', 'cctorrent.views.tagsearch', name='tagsearch'),
    url(r'^search', 'cctorrent.views.search', name='search'),
    url(r'^search', 'cctorrent.views.search', name='searchresult'),
    #url(r'^searchresult', 'cctorrent.views.search', name='searchresult'),
    url(r'^track/(\d+)/', 'cctorrent.views.track', name='track'),
    
    url(r'^user/(\d+)/newartist', 'cctorrent.views.newartist', name='newartist'),
    url(r'^user/(\d+)/', 'cctorrent.views.user', name='user'),
    url(r'^dashboard', 'cctorrent.views.dashboard', name='dashboard'),
    url(r'^importJamendo', 'cctorrent.views.importJamendo', name='importJamendo'),
    url(r'^usersettings', 'cctorrent.views.usersettings', name='usersettings'),
    
    #TODO: serve the following urls as static files => DONE!
    
    #CSS URLs:
    #url(r'^styles/basic', 'cctorrent.views.basicStyle', name='BasicStyle'),
    #url(r'^styles/color', 'cctorrent.views.colorScheme', name='ColorScheme'),
    
    #Logo URL:
    #url(r'^logo.png', 'cctorrent.views.logo', name='Logo'),
)

models.py
# -*- coding: utf-8 -*-
#
#   This file is part of cctorrent
#   Copyright (C) 2014-2015 Moritz Strohm <ncc1988@posteo.de>
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU Affero General Public License as
#   published by the Free Software Foundation, either version 3 of the
#   License, or (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU Affero General Public License for more details.
#
#   You should have received a copy of the GNU Affero General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator
#from django.db.models.signals import post_save


#TODO: reactivate if possible:
#class CCTorrentUser(models.User):
  #karma = models.IntegerField(default=0)
  #def __unicode__(self):
    #return self.username+" (karma: "+str(self.karma)+")"
    
  #def createCCTorrentUser(sender, instance, created, **kwargs):
    #if created:
     #CCTorrentUser.objects.create(user=instance)
  
  #post_save.connect(createCCTorrentUser, sender=User)


class Rating(models.Model):
  stars = models.PositiveIntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])
  comment = models.CharField(max_length=512)
  #TODO: add user reference (so that a user can't rate twice)
  #TODO: add ManyToManyFields in artist, album and track

class DonationInfo(models.Model):
  #place donation information into $description (e.g. Name+IBAN+BIC, Litecoin address,...)
  description = models.CharField(max_length=320)

class Tag(models.Model):
  name = models.CharField(primary_key=True, max_length=24)
  
  def __unicode__(self):
    return unicode(self.name)
  
class Artist(models.Model):
  name = models.CharField(max_length=256, unique=True)
  user = models.ForeignKey(User)
  description = models.TextField(default='')
  tags = models.ManyToManyField(Tag)
  def __unicode__(self):
    return unicode(self.name) + " (user: " + unicode(self.user.username) + ")"

class License(models.Model):
  short_name = models.CharField(max_length=16, unique=True)
  name = models.CharField(max_length=256)
  url = models.CharField(max_length=512)
  def __unicode__(self):
    return unicode(self.short_name)


class Album(models.Model):
  artist = models.ForeignKey(Artist) #TODO: rename to composer (or another word for someone who arranged the album)
  #TODO: add field artists (if more than one artist is present in the album)
  name = models.CharField(max_length=256)
  license = models.ForeignKey(License)
  pub_date = models.DateTimeField()
  finished = models.BooleanField(default=False) #if an album is finished it and its tracks can't be changed anymore
  tags = models.ManyToManyField(Tag)
  def __unicode__(self):
    return unicode(self.name)+" ("+unicode(self.artist.name)+")"
  
  def GetAlbumDirName(self):
    return self.artist.name + ' - ' + self.name

class Track(models.Model):
  name = models.CharField(max_length=256)
  artist = models.ForeignKey(Artist)
  #TODO: add field artists (if more than one artist made the track)
  license = models.ForeignKey(License)
  album = models.ForeignKey(Album)
  tags = models.ManyToManyField(Tag)
  number = models.IntegerField(default=0) #track number in album
  def __unicode__(self):
    return '{:02d}'.format(self.number) + " " + unicode(self.artist.name) + " - " + unicode(self.name)
    
  def formattedNumber():
    return '{:02d}'.format(self.number)
  
  def GetFileName(self):
    return '{:02d}'.format(self.number)+' '+str(self.name)
  
class UploadedAudioFile(models.Model):
  #this holds the path to an uploaded but not yet converted audio file
  #plus, all relevant information are stored in here to place the converted file in the right place
  fileName = models.CharField(max_length=4096)
  track = models.OneToOneField(Track, related_name="uploadedFile") #artist can be derived from track
  album = models.ForeignKey(Album) #a track may be placed in one or multiple albums
  uploaded = models.BooleanField(default=False)
  converted = models.BooleanField(default=False)
  errorOccured = models.BooleanField(default=False)
  errorStr = models.CharField(max_length=1024, default="")
  
  def __unicode__(self):
    string = self.fileName+' ('
    if(self.uploaded):
      string += "U"
    else:
      string += "u"
    if(self.converted):
      string += "C"
    else:
      string += "c"
    if(self.errorOccured):
      string += "E"
    else:
      string += "e"
    string += ')'
    return string


class RegisteredExtension(models.Model):
  #extensions have their own database table with important details about them
  uniqueName = models.CharField(max_length=256, unique=True) #can be: org.example.superExtension or simply a_new_extension or TheBestExtension or ...
  name = models.CharField(max_length=128) #the name that is shown to the user
  versionMajor = models.PositiveIntegerField(default=0)
  versionMinor = models.PositiveSmallIntegerField(default=0)
  
  homepage = models.URLField(max_length=256)
  author = models.CharField(max_length=192)
  authorMail = models.CharField(max_length=128, null=False)
  requiredCCTorrentAPIVersion = models.PositiveIntegerField(default=0) #the API version of CCTorrent that is required for an extension to work
  
  #TODO: extension dependencies (requires brain activity!)
  #dependencies = models.

class ExtensionSetting(models.Model):
  #extensions may store their configuration in the database as key-value pair
  extension = models.ForeignKey(RegisteredExtension)
  key = models.CharField(max_length=256, null=False)
  value = models.CharField(max_length=512, null=False)

forms/album.py
from django import forms
from cctorrent.models import License

class NewAlbumForm(forms.Form):
  name = forms.CharField(max_length=100)
  cover = forms.ImageField()
  publicationDate = forms.DateTimeField()
  licenseShort = forms.ModelChoiceField(queryset=None)
  tags = forms.CharField(max_length=100)
  
  def __init__(self, *args, **kwargs):
    super(NewAlbumForm, self).__init__(*args, **kwargs)
    self.fields['licenseShort'].queryset = License.objects.all() #licenseList

forms/artist.py
from django import forms

class NewArtistForm(forms.Form):
  name = forms.CharField(max_length=100)
  description = forms.CharField()
  picture = forms.ImageField()
  tags = forms.CharField(max_length=100)
  cryptocoinAddress = forms.CharField(required=False) #not yet in artist or user database model!!
  

forms/importJamendo.py
from django import forms
from cctorrent.models import Artist


class JamendoImportForm(forms.Form):
  #albumArtist = forms.ModelChoiceField(queryset=None, label="Album artist")
  albumArtistName = forms.CharField(max_length=256, label="Album artist")
  albumName = forms.CharField(max_length=256, label="Album name")
  zipFile = forms.FileField()
  #zipURL = forms.URLField(label="Album zip file URL")
  
  def __init__(self, *args, **kwargs):
    super(JamendoImportForm, self).__init__(*args, **kwargs)
    #self.fields['albumArtist'].queryset = Artist.objects.all()

forms/search.py
from django import forms

class GeneralSearchForm(forms.Form):
  term = forms.CharField(max_length=150)
  

templates/cctorrent/album.html
{% extends "cctorrent/base.html" %}
{% load CCTorrentFilters %}
{% comment %}
   This file is part of cctorrent
   Copyright (C) 2014-2015 Moritz Strohm <ncc1988@posteo.de>

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU Affero General Public License as
   published by the Free Software Foundation, either version 3 of the
   License, or (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU Affero General Public License for more details.

   You should have received a copy of the GNU Affero General Public License
   along with this program.  If not, see <http://www.gnu.org/licenses/>.
{% endcomment %}

{% block title %}{{album.name}} by {{album.artist.name}}{% endblock %}
{% block content %}
{% if album %}
  <div class="DetailHeader">
    <img class="DetailImage" src="{{ CCTORRENT_FILEURL }}album/{{album|GetAlbumDirName}}/cover.jpg"></img>
    <div class="DetailBox">
      <div class="DetailTitle">{{album.name}}</div>
      <table class="DetailTable">
        <tr>
          <td>Arranged by:</td>
          <td>
            <a href="{%url 'artist' album.artist.id%}">{{album.artist.name}}{% if loggedinUser.id == album.artist.user.id %} (you){% endif %}</a>
            <a class="Donation" href="./donate">Make donation</a>
          </td>
        </tr>
        <tr>
          <td>Release date:</td>
          <td>{{album.pub_date}}</td>
        </tr>
        <tr>
          <td>License:</td>
          <td>{{album.license.short_name}}</td>
        </tr>
        <tr class="TagLine">
          <td colspan="2">
          &nbsp;
          {% for t in album.tags.all %}
          <a href="{%url 'tagsearch' t %}">#{{t}}</a> 
          {% endfor %}
          </td>
        </tr>
        <tr>
          <td class="DownloadRow" colspan="2">
            {% if album.finished %}
            <a class="DownloadLink" href="{{ CCTORRENT_FILEURL }}album/{{album|GetAlbumDirName}}.torrent">Download album</a>
            <a class="DownloadTorrentInfo" href="{%url 'TorrentClients' %}">You need a BitTorrent client to download this album!</a>
            {% else %}
              {% if authenticated %}{% if loggedinUser.id == album.artist.user.id %}
              <div class="DownloadSubtitle">Note: The album has to be finished before it can be downloaded via the BitTorrent network</div>
              <a class="DownloadLink" href="{% url 'finishAlbum' album.id %}">Finish album</div>
              {% else %}
              <div class="DownloadSubtitle">The user <a href="{% url 'user' album.artist.user.id %}">{{album.artist.user}}</a> has not finished this album yet. Thus it is not yet available via BitTorrent.</div>
              {% endif %}{% endif %}
            {% endif %}
          </td>
        </tr>
      </table>
    </div>
  </div>
  <div class="DetailContent">
    <table class="TrackTable">
      <tr class="AlbumTrack">
        <th class="TrackArtist">Artist</th>
        <th class="TrackTitle">Title</th>
        <th class="TrackLicense">License</th>
        <th colspan="2" class="TrackPlayback"></th>
      </tr>
      {% for track in album.track_set.all %}
      <tr>
        <td class="TrackArtist">
          <a href="{%url 'artist' track.artist.id%}">{{track.artist.name}}</a>
        </td>
        <td class="TrackTitle">
          <a href="{%url 'track' track.id%}">{{track.name}}</a>
        </td>
        <td class="TrackLicense">
          <a href="{{track.license.url}}" target="_blank">{{track.license.short_name}}</a>
        </td>
        {% if track.uploadedFile.converted %}
        <td>
          <a href="{{CCTORRENT_FILEURL }}album/{{album|GetAlbumDirName}}/{{track|GetTrackFileName}}.ogg">download</a>
        </td>
        <td class="TrackPlayback">
          <audio src="{{ CCTORRENT_FILEURL }}album/{{album|GetAlbumDirName}}/{{track|GetTrackFileName}}.ogg" controls="controls" />
        </td>
        {% else %}
          {% if track.uploadedFile.uploaded %}
        <td colspan="2">
          The track is uploaded but not yet converted. Please wait a few minutes and try again.
        </td>
          {% else %}
        <td colspan="2">
          The track was not uploaded successfully. Something went wrong :(
        </td>
          {% endif %}
        {% endif %}
      </tr>
      {% endfor %}
    </table>
    {% if authenticated %}{% if loggedinUser.id == album.artist.user.id %}
    <a href="{%url 'newtrack' album.id%}">Add a new track to this album</a>
    {% endif %}{% endif %}
  </div>
  {%endif%}
{% endblock %}

templates/cctorrent/artist.html
{% extends "cctorrent/base.html" %}
{% load CCTorrentFilters %}

{% comment %}
   This file is part of cctorrent
   Copyright (C) 2014-2015 Moritz Strohm <ncc1988@posteo.de>

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU Affero General Public License as
   published by the Free Software Foundation, either version 3 of the
   License, or (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU Affero General Public License for more details.

   You should have received a copy of the GNU Affero General Public License
   along with this program.  If not, see <http://www.gnu.org/licenses/>.
{% endcomment %}

{% block title %}{{artist.name}}{% endblock %}
{% block content %}
{% if artist %}
  <div class="DetailHeader">
    <img class="DetailImage" src="{{CCTORRENT_FILEURL}}artist/{{artist.id}}/picture.jpg" />
    <div class="DetailBox">
      <div class="DetailTitle">{{artist.name}}</div>
      <div class="DetailSubtitle">
        {% if loggedinUser.id == artist.user.id %}
        (you manage this artist)
        {% else %}
        (managed by user {{artist.user.username}})
        {%endif%}
      </div>
      <div class="DetailText">{{artist.description}}</div>
      <div class="DetailFooter">
        {% for t in artist.tags.all %}
        <a href="{% url 'tagsearch' t.name %}">#{{t.name}}</a> 
        {% endfor %}
      </div>
    </div>
  </div>
  <div class="DetailContent">
    {% if loggedinUser.id != artist.user.id %}
      <h4>Albums of artist {{artist.name}}</h4>
    {% else %}
      <h4>Albums of your artist {{artist.name}}</h4>
    {% endif %}
    {% if albums %}
      {% for album in artist.album_set.all %}
      <div class="ItemBox">
        <a href="{% url 'album' album.id %}"><img class="ItemBoxImage" src="{{CCTORRENT_FILEURL}}album/{{album.id}}/cover.jpg" /></a>
        <div class="ItemBoxContent">
          <div><a class="ItemBoxLine ItemBoxName" href="{%url 'album' album.id %}">{{album.name}}</a></div>
          <div>by <a class="ItemBoxLine" href="{%url 'artist' album.artist.id %}">{{album.artist.name}}</a></div>
          <div class="ItemBoxLine">{{ album|GetAlbumTracks }} track(s)</div>
          <div><a class="ItemBoxLine" href="{{album.license.url}}" target="_blank">({{album.license.short_name}})</a></div>
          <div class="ItemBoxFooter">
          {% for t in album.tags.all %}
            <a href="{% url 'tagsearch' t.name %}">#{{t.name}}</a>
          {% endfor %}
          </div>
        </div>
      </div>
      <!--
      <div class="Square">
        <a href="{% url 'album' album.id %}">
          <img class="SquareImage" src="{{CCTORRENT_FILEURL}}album/{{album.id}}/cover.jpg" alt="{{album.name}}" />
        </a>
        <a href="{%url 'album' album.id %}" class="SquareTitle">{{album.name}}</a>
      </div>
      -->
      {% endfor %}
    {% else %}
      <div>This artist has not yet published any albums!</div>
    {% endif %}
    {% if loggedinUser.id == artist.user.id %}
      <div class="ItemBox">
        <a href="{% url 'newalbum' artist.id %}">
          <div class="ItemBoxAction">
            Create new album
          </div>
        </a>
      </div>
    {% endif %}
    </div>
{%endif%}
{% endblock %}

templates/cctorrent/base.html
{% comment %}
   This file is part of cctorrent
   Copyright (C) 2014-2015 Moritz Strohm <ncc1988@posteo.de>

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU Affero General Public License as
   published by the Free Software Foundation, either version 3 of the
   License, or (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU Affero General Public License for more details.

   You should have received a copy of the GNU Affero General Public License
   along with this program.  If not, see <http://www.gnu.org/licenses/>.
{% endcomment %}

{% load staticfiles %}
<?xml version="1.0" encoding="utf-8" ?>
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <title>{% block title %}{% endblock %} (CCTorrent)</title>
    <link rel="stylesheet" href="{% static "cctorrent/BasicStyle.css" %}" />
    <link rel="stylesheet" href="{% static "cctorrent/ColorScheme.css" %}" />
    <script type="text/javascript" src="{% url 'settingsJS' %}" ></script>
    <script type="text/javascript" src="{% static "cctorrent/CCTorrent.js" %}"></script>
  </head>
  <body>
    <div id="MainMenu">
      <a href="{% url 'index' %}">
        <img style="display:inline; max-height: 1.5em;" src="{% static "cctorrent/cctorrent-logo.png" %}" alt="cctorrent-logo"></img>
      </a>
      <a href="{%url 'search' %}">Search</a>
      {%if authenticated %}
        <a id="UserSettingsButton" href="{%url 'dashboard' %}">Dashboard</a>
        <a id="UserLoginButton" href="{% url 'logout' %}">Logout</a>
      {%else%}
        {{CCTorrentConfig.DemoMode}}
        {% if CCTorrentConfig.DemoMode %}
        <span>Demo</span>
        {% else %}
        <a id="UserLoginButton" href="{% url 'login' %}">Login</a>
        {% endif %}
      {%endif%}
    </div>
    <div id="MainContent">
      {% if errorList %}
        <ul class="ErrorList">
        {% for e in errorList %}
          <li>{{e}}</li>
        {% endfor %}
        </ul>
      {% endif %}
      {% block content %}

      {% endblock %}
    </div>
  </body>
</html>

templates/cctorrent/dashboard.html
{% extends "cctorrent/base.html" %}

{% comment %}
   This file is part of cctorrent
   Copyright (C) 2014-2015 Moritz Strohm <ncc1988@posteo.de>

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU Affero General Public License as
   published by the Free Software Foundation, either version 3 of the
   License, or (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU Affero General Public License for more details.

   You should have received a copy of the GNU Affero General Public License
   along with this program.  If not, see <http://www.gnu.org/licenses/>.
{% endcomment %}

{% block title %}{{loggedinUser.username}}{% endblock %}
{% block content %}
{% if loggedinUser %}
  <!--<h2>Dashboard of {{loggedinUser.username}}<h2>-->
  <table id="DashboardTable" style="width:95%; height:70%;">
    <tr style="height:1.5em;vertical-align:middle;text-align:center;font-weight:bold;">
      <td colspan="2">
      {% if Notification %}{{Notification}}{% endif %}
      </td>
    </tr>
    <tr id="DashboardTableTopRow">
      <td class="DashboardTableLeft">
        <h3>News</h3>
        <!-- STUB -->
        <ul id="DashboardNewsList">
          <li><span class="NewsDate">2015-01-01:</span> <span><a href="{% url 'user' 1 %}">Moéééé</a> commented on your album <a href="{% url 'album' 1 %}">Test</a></span></li>
          <li><span class="NewsDate">2014-12-08:</span> <span><a href="{% url 'user' 2 %}">Guybrush</a> started following you</span>
          <li><span class="NewsDate">2014-11-11:</span> <span><a href="{% url 'user' 3 %}">Lisa</a> started following you</span>
          <li><span class="NewsDate">2014-08-05:</span> <span><a href="{% url 'user' 2 %}">Guybrush</a> stopped following you</span>
          <li><span class="NewsDate">2014-08-01:</span> <span>Your album <a href="{% url 'album' 1 %}">Test</a> was released!</span>
        </ul>
      </td>
      <td>
        <h3>Your actions</h3>
        <a class="DashboardAction" href="{% url 'newartist' loggedinUser.id %}">
          <img class="DashboardActionIcon" src="/static/cctorrent/icons/NewArtist.png" />
          <div>New artist</div>
        </a>
        <a class="DashboardAction" href="{% url 'importJamendo' %}">
          <img class="DashboardActionIcon" src="/static/cctorrent/icons/Upload.png" />
          <div>Import Jamendo</div>
        </a>
      </td>
    </tr>
    <tr>
      <td colspan="2">
        <h3>Your artists</h3>
        {% if loggedinUser.artist_set.all %}
	  <div id="DashboardArtistSquares">
          {% for artist in loggedinUser.artist_set.all %}
	    <div class="Square">
	      <a href="{% url 'artist' artist.id %}">
		<img class="SquareImage" src="{{CCTORRENT_FILEURL}}artist/{{artist.id}}/picture.jpg"/>
	      </a>
	      <a class="SquareTitle" href="{%url 'artist' artist.id%}">{{artist.name}}</a>
	    </div>        
          {% endfor %}
          </div>
        {% else %}
        <p>You haven't created any artist!</p>
        {% endif %}
      </td>
    </tr>
  </table>
{%endif%}
{% endblock %}

templates/cctorrent/importJamendo.html
{% extends "cctorrent/base.html" %}

{% comment %}
   This file is part of cctorrent
   Copyright (C) 2014-2015 Moritz Strohm <ncc1988@posteo.de>

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU Affero General Public License as
   published by the Free Software Foundation, either version 3 of the
   License, or (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU Affero General Public License for more details.

   You should have received a copy of the GNU Affero General Public License
   along with this program.  If not, see <http://www.gnu.org/licenses/>.
{% endcomment %}

{% block title %}Import a Jamendo album{% endblock %}
{% block content %}
{% if authenticated == True %}
  <h3>Import a Jamendo album<h3>
  <form enctype="multipart/form-data" action="{%url 'importJamendo' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    {% if errorList %}
    <p>Errors:</p>
    <ul>
      {% for error in errorList %}
      <li>{{ error }}</li>
      {% endfor %}
    </ul>
    {% endif %}
    <input type="submit" value="Import Jamendo zip"/>
  </form>
{% else %}
  <h3>Not allowed!</h3>
  <p>You must <a href="{%url 'login' %}">log in</a> to import a Jamendo album!</p>
{%endif%}
{% endblock %}

templates/cctorrent/usersettings.html
{% extends "cctorrent/base.html" %}

{% comment %}
   This file is part of cctorrent
   Copyright (C) 2014-2015 Moritz Strohm <ncc1988@posteo.de>

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU Affero General Public License as
   published by the Free Software Foundation, either version 3 of the
   License, or (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU Affero General Public License for more details.

   You should have received a copy of the GNU Affero General Public License
   along with this program.  If not, see <http://www.gnu.org/licenses/>.
{% endcomment %}

{% block title %}{{user.name}}{% endblock %}
{% block content %}
{% if user %}
  <h3>{{user.name}}<h3>
  <h4>Artist names:</h4>
  <ul>
  {% for artist in user.artist_set.all %}
    <li><a href="./artist/{{artist.id}}">{{artist.name}}</a></li>
  {% endfor %}
  </ul>
  {% if authenticated %}
  <a href="{% url 'newartist' user.id %}">Create artist profile</a>
  {% endif %}
{%endif%}
{% endblock %}